### ISSUE TITLE
When we add any line or any text after the response line, the response comes empty in the sample editor window. see an example below.

### ISSUE THREAD

**Issue by mirairani** [apalsapure/oski-dev-center#130]
+ Response 200 (application/json)
    + Attributes (searchInitResponse)

<a name="GetSearchResultsAPI"></a>

even with a blank line after the response it doesn't work.

**Comment by apalsapure** [comment]
Use `#` before anchor tag and add class `hide-parent` to anchor
eg
# <a name="rectangular" class="hide-parent"></a>
