### ISSUE TITLE
Example values not appearing for boolean values.

### ISSUE THREAD

**Issue by mirairani** [apalsapure/oski-dev-center#191]

**Comment by apalsapure** [comment]
Where can I see a sample?

**Comment by mirairani** [comment]
Will send screen shot - sorry I missed attaching it.

**Comment by mirairani** [comment]
<img width="1230" alt="screen shot 2017-02-03 at 2 02 40 am" src="https://cloud.githubusercontent.com/assets/17611575/22567190/ee25c41e-e9b4-11e6-9aae-d5c85b17bab8.png">
