### ISSUE TITLE
Title, descriptions and keywords

### ISSUE THREAD

**Issue by apalsapure** [apalsapure/oski-dev-center#223]
For SEO all the pages should have proper title, description and keywords. 

- Title should have proper hierarchy e.g. Search - Hotel - Booking Engine - Dev Center - Oski
- Description should explain not more than 150 characters
- Keywords are the words which are present on that page with density not more than 8%

**Comment by apalsapure** [comment]
@mirairani when is this scheduled?

**Comment by mirairani** [comment]
@apalsapure Marked as lowest priority in the task list as of now. Should get to it in about 2-3 months.

**Comment by apalsapure** [comment]
@mirairani FYI google is crawling the website. And google takes a long time to update it's search database. So if you take up this task after 2-3 months, google will take another 2-3 months to update it's index, till that time end user will stale content in the search.

**Comment by mirairani** [comment]
@apalsapure Will need to discuss this with NP and Asmita as the prioritization of tasks comes from them. Will note it down and let you know. For now, this cannot be taken up in April at least. Will discuss with them about fitting this around May.
