### ISSUE TITLE
Dev Center returns something went wrong for a 204 response call...

### ISSUE THREAD

**Issue by mirairani** [apalsapure/oski-dev-center#253]
Sample: Cancellation call for both hotel and car 

screenshots attached 
<img width="731" alt="screen shot 2017-03-07 at 6 57 10 pm" src="https://cloud.githubusercontent.com/assets/17611575/23658293/f44fd0c4-0367-11e7-8326-301ec1563bd1.png">
<img width="775" alt="screen shot 2017-03-07 at 6 57 17 pm" src="https://cloud.githubusercontent.com/assets/17611575/23658295/f48c56f2-0367-11e7-9c73-58f9765a8cb3.png">

**Comment by apalsapure** [comment]
Fix is in master and deployed on prod
