### ISSUE TITLE
Need to add full path for each field... 

### ISSUE THREAD

**Issue by mirairani** [apalsapure/oski-dev-center#454]
Hi Amar, 

Per the recent feedback we have received, due to the nested nature of our contracts, specially in the response, we would like to request for the user to have the facility to view the full path for each field as and when required. Please let me know if you need any clarification or further information on this enhancement request.

Thanks.

-Mira

**Comment by apalsapure** [comment]
Fixed in https://github.com/apalsapure/oski-dev-center/pull/464
