### ISSUE TITLE
Need a navigation panel with the complete documentation workflow to appear all the internal pages.

### ISSUE THREAD

**Issue by smritiprasad** [apalsapure/oski-dev-center#455]
For example, The hotel engine home page navigation panel (left side) has the below documentation workflow, we would like this navigation panel to appear on all internal pages so that the user can navigate from one page to another page with clear understanding of where he/she is within the hotel documentation workflow. This enhancement would definitely make the navigation easy and user-friendly.
This means that if the user is on the Search page and wants to navigate from Search page to Book page, he/she can do so by clicking on the navigation panel. 

Overview
Search 
RoomList
Price
Book
Cancel
Status and Error Codes
Glossary
Reference reads

This feedback is provided by Amit L, Pramod J, Mira, Smriti, Tokas.

**Comment by apalsapure** [comment]
Add `_common.json` in product folder. In this JSON, add object `index` with `actions` as an array. Actions defined in overview are now shifted to above file. Now these actions are shared across all pages related to respective product.
If you don't want inline navigation; set `hideInlineNavigation` to `true` in the respective `_data.json` file.
