### ISSUE TITLE
Add a feature that allows the user to collapse all the JSON Properties in the Request and Response Body

### ISSUE THREAD

**Issue by smritiprasad** [apalsapure/oski-dev-center#516]
The current implementation in the Dev center is such that, by default, the JSON Request and Response body comes expanded in both the Sample view and the Try It Now view.  The user cannot collapse all the JSON Properties present at the root level at once, instead the user has to collapse each JSON Property individually.  
We would like an enhancement in the Dev center which allows the user to collapse all the JSON Properties at the root level at a click of a button.

**Comment by apalsapure** [comment]
This feature is already provided by the editor in terms of keyboard shortcut. In try out mode use `Ctrl + K, Ctrl + 2` to collapse. To view list of all commands press `F1` in the editor.
