### ISSUE TITLE
Add enhancement to add Sample JSON as a popover in the field description

### ISSUE THREAD

**Issue by smritiprasad** [apalsapure/oski-dev-center#532]
The current implementation for popover does not allow us to add sample JSON code snippet in the popover. This enhancement would allow us to add sample JSON code snippet within the field description to help the developer to understand the implementation and integrate with the API properly. 

Use of <code></code> puts each line of the Sample JSON in the  broken box. 
Use of <` `> does render the code properly in the field description. 

We would like that when the user hovers over this text <Click to view the Sample JSON with the required fields provided:>, the below sample JSON should appear as a popup. 
For example, Guests array in Initiate Book Request
"guests": [<br>
        {<br>
          "type": "Adult",<br>
          "name": {<br>
            "first": "John"<br>
          },<br>
        },<br>
  {<br>
          "type": "Child",<br>
          "name": {<br>
            "first": "Jane"<br>
          },<br>
          "age": 12<br>
        }<br>
  ]<br>

**Comment by apalsapure** [comment]
Support for this is added in new dev center. Use `_glossary.json` for this. Sample implementation is done in hotel booking engine
