### ISSUE TITLE
Need automation of sample data for dates - sent email

### ISSUE THREAD

**Issue by mirairani** [apalsapure/oski-dev-center#87]
Need automation of sample data for dates - sent email

**Comment by apalsapure** [comment]
Added support in https://github.com/apalsapure/oski-dev-center/pull/107

**Comment by apalsapure** [comment]
**Format:** {date|YYYY-MM-DD|20}
In above format, start and end should be  `{` and `}`.
For date operations, use `date` after `{`
Then the format of date required (eq. YYYY-MM-##), separated by `|`. For the formats go through http://momentjs.com/docs/#/displaying/.
Last is the number of days, which will be added to current date (eq. 20) again separated by `|`
